name:                l3
version:             0.1.0.0
github:              "githubuser/l3"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/l3#readme>

dependencies:
  - base >= 4.7 && < 5
  - diagnose == 2.0.0
  - megaparsec == 9.2.1
  - text ==1.2.5.0
  - optparse-applicative ==0.17.0.0
  - hspec-megaparsec ==2.2.0
  - hspec ==2.10.0.1
  - containers == 0.6.5.1
  - mtl == 2.2.2

library:
  source-dirs: src

executables:
  l3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - l3

tests:
  l3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - l3
